export const product = [
    {
        id: 0,
        type:"Vegetable",
        imageId: "avacado_1",
        price: 123,
        name: "Avacado",
    },
    {
        id: 1,
        type:"Fruit",
        imageId: "mango_1",
        price: 87,
        name: "Mango",
    },
    {
        id: 2,
        type:"Vegetable",
        imageId: "pea_1",
        price: 40,
        name: "Pea",
    },
    {
        id: 3,
        type:"Vegetable",
        imageId: "potato_1",
        price: 10,
        name: "Potato",
    },
    {
        id: 4,
        type:"Fruit",
        imageId: "watermalone_1",
        price: 60,
        name: "Watermelon",
    },
    {
        id: 5,
        type:"Vegetable",
        imageId: "onionRed_1",
        price: 56,
        name: "Red Onion",
    },
    {
        id: 6,
        type:"Fruit",
        imageId: "pomegranate_1",
        price: 65,
        name: "Pomegranate",
    },
    {
        id: 7,
        type:"Vegetable",
        imageId: "tomato_1",
        price: 43,
        name: "Tomatoes",
    },
    {
        id: 8,
        type:"Vegetable",
        imageId: "mashroom_1",
        price: 124,
        name: "Mashroom",
    },
    {
        id: 9,
        type:"Fruit",
        imageId: "guava_1",
        price: 45,
        name: "Guava",
    },
    {
        id: 10,
        type:"Vegetable",
        imageId: "carrot_2",
        price: 32,
        name: "Carrot",
    },
    {
        id: 11,
        type:"Vegetable",
        imageId: "onionWhite_1",
        price: 68,
        name: "White Onion",
    },
    {
        id: 12,
        type:"Fruit",
        imageId: "kiwi_1",
        price: 89,
        name: "Kiwi",
    },
    {
        id: 13,
        type:"Fruit",
        imageId: "orange_1",
        price: 90,
        name: "Orange",
    },
    {
        id: 14,
        type:"Vegetable",
        imageId: "garlic_1",
        price: 65,
        name: "Garlic",
    },
    {
        id: 15,
        type:"Vegetable",
        imageId: "cucumber_1",
        price: 56,
        name: "Cucumber",
    }

]